data:
  - "${INPUT_DATA}"

output_dir: "${OUTPUT_DIR}"

tokenizer:
  name: "char"

seed: 22

preprocessing:
  - type: "switch"
    arguments:
      functions:
        - type: "whitespace_corruption"
          arguments:
            iw_p: 0.1
            dw_p: 0.2
            seed: 22
        - type: "whitespace_corruption"
          arguments:
            no_ws: true
        - type: "whitespace_corruption"
          arguments:
            full_ws: true
      prob: [ 0.8, 0.1, 0.1 ]
      seed: 23
  - type: "whitespace_correction"
    arguments:
      output_type: "label"
  - type: "whitespace_subsampling"
    arguments:
      length: 510

lmdb_name: "lmdb"
max_sequence_length: 512
