port: 40000
timeout: 10
# allow_origin: test.mydomain.com 
base_url: env(BASE_URL:/api)
models:
  # load a pretrained model by specifying the name
  # - name: eo_large_arxiv
  # load a model from a local experiment by specifying the
  # directory path (you can use special configuration operators,
  # e.g. env(ENV_VAR) to load env variables)
  - path: env(EXPERIMENT)
batch_size: env(BATCH_SIZE:16)
# batch_max_tokens: env(BATCH_MAX_TOKENS:8192)
